[2022-12-12 17:09:51,836] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T17:08:46.180704+00:00 [queued]>
[2022-12-12 17:09:51,841] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T17:08:46.180704+00:00 [queued]>
[2022-12-12 17:09:51,842] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 17:09:51,842] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-12-12 17:09:51,842] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 17:09:51,850] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_pdf_task> on 2022-12-12 17:08:46.180704+00:00
[2022-12-12 17:09:51,854] {standard_task_runner.py:52} INFO - Started process 600 to run task
[2022-12-12 17:09:51,857] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'daily_paper', 'create_pdf_task', 'manual__2022-12-12T17:08:46.180704+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/morning-paper.py', '--cfg-path', '/tmp/tmpm8b5tgzy', '--error-file', '/tmp/tmp285z8qtn']
[2022-12-12 17:09:51,858] {standard_task_runner.py:80} INFO - Job 207: Subtask create_pdf_task
[2022-12-12 17:09:51,903] {task_command.py:369} INFO - Running <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T17:08:46.180704+00:00 [running]> on host 6bb81baa0a52
[2022-12-12 17:09:51,954] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=daily_paper
AIRFLOW_CTX_TASK_ID=create_pdf_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T17:08:46.180704+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T17:08:46.180704+00:00
[2022-12-12 17:09:51,965] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/morning_paper_src/pdf.py", line 44, in create_pdf
    regular(pdf, convert_unicode(news['summary']))
  File "/opt/airflow/dags/morning_paper_src/pdf.py", line 21, in regular
    pdf.multi_cell(0, 10, text, 0, 1)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 150, in wrapper
    return fn(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 784, in multi_cell
    s=txt.replace("\r",'')
TypeError: a bytes-like object is required, not 'str'
[2022-12-12 17:09:51,974] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=daily_paper, task_id=create_pdf_task, execution_date=20221212T170846, start_date=20221212T170951, end_date=20221212T170951
[2022-12-12 17:09:51,980] {standard_task_runner.py:97} ERROR - Failed to execute job 207 for task create_pdf_task (a bytes-like object is required, not 'str'; 600)
[2022-12-12 17:09:51,989] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 17:09:52,010] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
