[2022-12-12 17:54:34,655] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T17:54:29.414620+00:00 [queued]>
[2022-12-12 17:54:34,660] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T17:54:29.414620+00:00 [queued]>
[2022-12-12 17:54:34,660] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 17:54:34,661] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-12 17:54:34,661] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 17:54:34,668] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_pdf_task> on 2022-12-12 17:54:29.414620+00:00
[2022-12-12 17:54:34,671] {standard_task_runner.py:52} INFO - Started process 1537 to run task
[2022-12-12 17:54:34,674] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'daily_paper', 'create_pdf_task', 'manual__2022-12-12T17:54:29.414620+00:00', '--job-id', '308', '--raw', '--subdir', 'DAGS_FOLDER/morning-paper.py', '--cfg-path', '/tmp/tmpfwa19wbv', '--error-file', '/tmp/tmp7mg703od']
[2022-12-12 17:54:34,676] {standard_task_runner.py:80} INFO - Job 308: Subtask create_pdf_task
[2022-12-12 17:54:34,715] {task_command.py:369} INFO - Running <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T17:54:29.414620+00:00 [running]> on host 6bb81baa0a52
[2022-12-12 17:54:34,762] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=daily_paper
AIRFLOW_CTX_TASK_ID=create_pdf_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T17:54:29.414620+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T17:54:29.414620+00:00
[2022-12-12 17:54:34,775] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/morning_paper_src/pdf.py", line 48, in create_pdf
    regular(pdf, 'summary ' + news['summary'].replace('\n', ' '))
AttributeError: 'NoneType' object has no attribute 'replace'
[2022-12-12 17:54:34,784] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_paper, task_id=create_pdf_task, execution_date=20221212T175429, start_date=20221212T175434, end_date=20221212T175434
[2022-12-12 17:54:34,790] {standard_task_runner.py:97} ERROR - Failed to execute job 308 for task create_pdf_task ('NoneType' object has no attribute 'replace'; 1537)
[2022-12-12 17:54:34,806] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 17:54:34,827] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
