[2022-12-12 17:39:09,405] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T17:39:05.538894+00:00 [queued]>
[2022-12-12 17:39:09,410] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T17:39:05.538894+00:00 [queued]>
[2022-12-12 17:39:09,410] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 17:39:09,410] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-12 17:39:09,411] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 17:39:09,418] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_pdf_task> on 2022-12-12 17:39:05.538894+00:00
[2022-12-12 17:39:09,421] {standard_task_runner.py:52} INFO - Started process 1169 to run task
[2022-12-12 17:39:09,424] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'daily_paper', 'create_pdf_task', 'manual__2022-12-12T17:39:05.538894+00:00', '--job-id', '284', '--raw', '--subdir', 'DAGS_FOLDER/morning-paper.py', '--cfg-path', '/tmp/tmpd0b2q2ag', '--error-file', '/tmp/tmpjqm1eb1d']
[2022-12-12 17:39:09,425] {standard_task_runner.py:80} INFO - Job 284: Subtask create_pdf_task
[2022-12-12 17:39:09,463] {task_command.py:369} INFO - Running <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T17:39:05.538894+00:00 [running]> on host 6bb81baa0a52
[2022-12-12 17:39:09,508] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=daily_paper
AIRFLOW_CTX_TASK_ID=create_pdf_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T17:39:05.538894+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T17:39:05.538894+00:00
[2022-12-12 17:39:09,520] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/morning_paper_src/pdf.py", line 42, in create_pdf
    regular(pdf, 'title ' + news['title'])
TypeError: string indices must be integers
[2022-12-12 17:39:09,528] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_paper, task_id=create_pdf_task, execution_date=20221212T173905, start_date=20221212T173909, end_date=20221212T173909
[2022-12-12 17:39:09,534] {standard_task_runner.py:97} ERROR - Failed to execute job 284 for task create_pdf_task (string indices must be integers; 1169)
[2022-12-12 17:39:09,557] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 17:39:09,578] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
