[2022-12-12 12:07:08,662] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_Paper.get_joke_task manual__2022-12-12T12:07:07.327486+00:00 [queued]>
[2022-12-12 12:07:08,667] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_Paper.get_joke_task manual__2022-12-12T12:07:07.327486+00:00 [queued]>
[2022-12-12 12:07:08,668] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 12:07:08,669] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-12 12:07:08,669] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 12:07:08,678] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_joke_task> on 2022-12-12 12:07:07.327486+00:00
[2022-12-12 12:07:08,683] {standard_task_runner.py:52} INFO - Started process 197 to run task
[2022-12-12 12:07:08,690] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'daily_Paper', 'get_joke_task', 'manual__2022-12-12T12:07:07.327486+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/morning-paper.py', '--cfg-path', '/tmp/tmp26r41t6e', '--error-file', '/tmp/tmpp0vsc8yo']
[2022-12-12 12:07:08,692] {standard_task_runner.py:80} INFO - Job 5: Subtask get_joke_task
[2022-12-12 12:07:08,771] {task_command.py:369} INFO - Running <TaskInstance: daily_Paper.get_joke_task manual__2022-12-12T12:07:07.327486+00:00 [running]> on host cbcd6542cb8e
[2022-12-12 12:07:08,865] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=daily_Paper
AIRFLOW_CTX_TASK_ID=get_joke_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T12:07:07.327486+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T12:07:07.327486+00:00
[2022-12-12 12:07:09,910] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/morning-paper.py", line 32, in get_joke
    if res.status_code != 200 or joke_dict['error'] == True:
UnboundLocalError: local variable 'joke_dict' referenced before assignment
[2022-12-12 12:07:09,920] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_Paper, task_id=get_joke_task, execution_date=20221212T120707, start_date=20221212T120708, end_date=20221212T120709
[2022-12-12 12:07:09,926] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task get_joke_task (local variable 'joke_dict' referenced before assignment; 197)
[2022-12-12 12:07:09,964] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 12:07:09,991] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
