[2022-12-12 16:23:09,988] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T16:22:04.806682+00:00 [queued]>
[2022-12-12 16:23:09,994] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T16:22:04.806682+00:00 [queued]>
[2022-12-12 16:23:09,995] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 16:23:09,995] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-12-12 16:23:09,996] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 16:23:10,003] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_pdf_task> on 2022-12-12 16:22:04.806682+00:00
[2022-12-12 16:23:10,006] {standard_task_runner.py:52} INFO - Started process 2869 to run task
[2022-12-12 16:23:10,011] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'daily_paper', 'create_pdf_task', 'manual__2022-12-12T16:22:04.806682+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/morning-paper.py', '--cfg-path', '/tmp/tmpoalwjebm', '--error-file', '/tmp/tmp60gt06jl']
[2022-12-12 16:23:10,012] {standard_task_runner.py:80} INFO - Job 121: Subtask create_pdf_task
[2022-12-12 16:23:10,059] {task_command.py:369} INFO - Running <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T16:22:04.806682+00:00 [running]> on host cbcd6542cb8e
[2022-12-12 16:23:10,111] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=daily_paper
AIRFLOW_CTX_TASK_ID=create_pdf_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T16:22:04.806682+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T16:22:04.806682+00:00
[2022-12-12 16:23:10,121] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/morning_paper_src/pdf.py", line 35, in create_pdf
    pdf.h1(title)
AttributeError: 'FPDF' object has no attribute 'h1'
[2022-12-12 16:23:10,130] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=daily_paper, task_id=create_pdf_task, execution_date=20221212T162204, start_date=20221212T162309, end_date=20221212T162310
[2022-12-12 16:23:10,136] {standard_task_runner.py:97} ERROR - Failed to execute job 121 for task create_pdf_task ('FPDF' object has no attribute 'h1'; 2869)
[2022-12-12 16:23:10,184] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 16:23:10,207] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
