[2022-12-13 07:53:17,766] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: cereal_paper.create_pdf_task manual__2022-12-13T07:52:11.965299+00:00 [queued]>
[2022-12-13 07:53:17,773] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: cereal_paper.create_pdf_task manual__2022-12-13T07:52:11.965299+00:00 [queued]>
[2022-12-13 07:53:17,774] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 07:53:17,774] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-12-13 07:53:17,774] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 07:53:17,783] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_pdf_task> on 2022-12-13 07:52:11.965299+00:00
[2022-12-13 07:53:17,786] {standard_task_runner.py:52} INFO - Started process 285 to run task
[2022-12-13 07:53:17,789] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'cereal_paper', 'create_pdf_task', 'manual__2022-12-13T07:52:11.965299+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/cereal-paper.py', '--cfg-path', '/tmp/tmpfr9rf472', '--error-file', '/tmp/tmpuec3m5qa']
[2022-12-13 07:53:17,791] {standard_task_runner.py:80} INFO - Job 25: Subtask create_pdf_task
[2022-12-13 07:53:17,853] {task_command.py:369} INFO - Running <TaskInstance: cereal_paper.create_pdf_task manual__2022-12-13T07:52:11.965299+00:00 [running]> on host 5029e27bd97f
[2022-12-13 07:53:17,942] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=cereal_paper
AIRFLOW_CTX_TASK_ID=create_pdf_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-13T07:52:11.965299+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-13T07:52:11.965299+00:00
[2022-12-13 07:53:17,957] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cereal_paper_src/pdf.py", line 37, in create_pdf
    pdf.add_font('SpecialElite', '', '.dags/cereal_paper_src/SpecialElite.ttf', uni=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 469, in add_font
    raise RuntimeError("TTF Font file not found: %s" % fname)
RuntimeError: TTF Font file not found: .dags/cereal_paper_src/SpecialElite.ttf
[2022-12-13 07:53:17,974] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=cereal_paper, task_id=create_pdf_task, execution_date=20221213T075211, start_date=20221213T075317, end_date=20221213T075317
[2022-12-13 07:53:17,981] {standard_task_runner.py:97} ERROR - Failed to execute job 25 for task create_pdf_task (TTF Font file not found: .dags/cereal_paper_src/SpecialElite.ttf; 285)
[2022-12-13 07:53:18,001] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-13 07:53:18,040] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
