[2022-12-13 07:52:16,902] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: cereal_paper.create_pdf_task manual__2022-12-13T07:52:11.965299+00:00 [queued]>
[2022-12-13 07:52:16,908] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: cereal_paper.create_pdf_task manual__2022-12-13T07:52:11.965299+00:00 [queued]>
[2022-12-13 07:52:16,908] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 07:52:16,908] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-13 07:52:16,909] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 07:52:16,917] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_pdf_task> on 2022-12-13 07:52:11.965299+00:00
[2022-12-13 07:52:16,920] {standard_task_runner.py:52} INFO - Started process 254 to run task
[2022-12-13 07:52:16,923] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'cereal_paper', 'create_pdf_task', 'manual__2022-12-13T07:52:11.965299+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/cereal-paper.py', '--cfg-path', '/tmp/tmpdcsk_6y2', '--error-file', '/tmp/tmpegzpvb0t']
[2022-12-13 07:52:16,924] {standard_task_runner.py:80} INFO - Job 22: Subtask create_pdf_task
[2022-12-13 07:52:16,981] {task_command.py:369} INFO - Running <TaskInstance: cereal_paper.create_pdf_task manual__2022-12-13T07:52:11.965299+00:00 [running]> on host 5029e27bd97f
[2022-12-13 07:52:17,058] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=cereal_paper
AIRFLOW_CTX_TASK_ID=create_pdf_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-13T07:52:11.965299+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-13T07:52:11.965299+00:00
[2022-12-13 07:52:17,073] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cereal_paper_src/pdf.py", line 44, in create_pdf
    h1(pdf, title)
  File "/opt/airflow/dags/cereal_paper_src/pdf.py", line 12, in h1
    pdf.set_font_size(20)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 621, in set_font_size
    self._out(sprintf('BT /F%d %.2f Tf ET',self.current_font['i'],self.font_size_pt))
AttributeError: 'FPDF' object has no attribute 'current_font'
[2022-12-13 07:52:17,090] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=cereal_paper, task_id=create_pdf_task, execution_date=20221213T075211, start_date=20221213T075216, end_date=20221213T075217
[2022-12-13 07:52:17,098] {standard_task_runner.py:97} ERROR - Failed to execute job 22 for task create_pdf_task ('FPDF' object has no attribute 'current_font'; 254)
[2022-12-13 07:52:17,136] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-13 07:52:17,178] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
