[2022-12-13 07:51:32,642] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: cereal_paper.create_pdf_task scheduled__2022-12-12T00:00:00+00:00 [queued]>
[2022-12-13 07:51:32,649] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: cereal_paper.create_pdf_task scheduled__2022-12-12T00:00:00+00:00 [queued]>
[2022-12-13 07:51:32,649] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 07:51:32,650] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-13 07:51:32,650] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 07:51:32,660] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_pdf_task> on 2022-12-12 00:00:00+00:00
[2022-12-13 07:51:32,662] {standard_task_runner.py:52} INFO - Started process 220 to run task
[2022-12-13 07:51:32,667] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'cereal_paper', 'create_pdf_task', 'scheduled__2022-12-12T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/cereal-paper.py', '--cfg-path', '/tmp/tmpo1iyczw8', '--error-file', '/tmp/tmpdc15i6fi']
[2022-12-13 07:51:32,668] {standard_task_runner.py:80} INFO - Job 14: Subtask create_pdf_task
[2022-12-13 07:51:32,735] {task_command.py:369} INFO - Running <TaskInstance: cereal_paper.create_pdf_task scheduled__2022-12-12T00:00:00+00:00 [running]> on host 5029e27bd97f
[2022-12-13 07:51:32,818] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=cereal_paper
AIRFLOW_CTX_TASK_ID=create_pdf_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-12T00:00:00+00:00
[2022-12-13 07:51:33,058] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cereal_paper_src/pdf.py", line 85, in create_pdf
    pdf.output('./temp/cereal_paper.pdf', 'F')
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 1065, in output
    self.close()
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 246, in close
    self._enddoc()
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 1637, in _enddoc
    self._putresources()
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 1584, in _putresources
    self._putfonts()
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 1288, in _putfonts
    ttfontstream = ttf.makeSubset(font['ttffile'], subset)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/ttfonts.py", line 459, in makeSubset
    self.fh = open(file ,'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/morning_paper_src/SpecialElite.ttf'
[2022-12-13 07:51:33,077] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=cereal_paper, task_id=create_pdf_task, execution_date=20221212T000000, start_date=20221213T075132, end_date=20221213T075133
[2022-12-13 07:51:33,090] {standard_task_runner.py:97} ERROR - Failed to execute job 14 for task create_pdf_task ([Errno 2] No such file or directory: '/opt/airflow/dags/morning_paper_src/SpecialElite.ttf'; 220)
[2022-12-13 07:51:33,122] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-13 07:51:33,167] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
