[2022-12-13 07:52:33,287] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: cereal_paper.create_pdf_task scheduled__2022-12-12T00:00:00+00:00 [queued]>
[2022-12-13 07:52:33,303] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: cereal_paper.create_pdf_task scheduled__2022-12-12T00:00:00+00:00 [queued]>
[2022-12-13 07:52:33,304] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 07:52:33,304] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-12-13 07:52:33,305] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-13 07:52:33,316] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_pdf_task> on 2022-12-12 00:00:00+00:00
[2022-12-13 07:52:33,322] {standard_task_runner.py:52} INFO - Started process 263 to run task
[2022-12-13 07:52:33,326] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'cereal_paper', 'create_pdf_task', 'scheduled__2022-12-12T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/cereal-paper.py', '--cfg-path', '/tmp/tmpe20p35o4', '--error-file', '/tmp/tmph6wtpze7']
[2022-12-13 07:52:33,327] {standard_task_runner.py:80} INFO - Job 24: Subtask create_pdf_task
[2022-12-13 07:52:33,410] {task_command.py:369} INFO - Running <TaskInstance: cereal_paper.create_pdf_task scheduled__2022-12-12T00:00:00+00:00 [running]> on host 5029e27bd97f
[2022-12-13 07:52:33,493] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=cereal_paper
AIRFLOW_CTX_TASK_ID=create_pdf_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-12T00:00:00+00:00
[2022-12-13 07:52:33,511] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cereal_paper_src/pdf.py", line 44, in create_pdf
    h1(pdf, title)
  File "/opt/airflow/dags/cereal_paper_src/pdf.py", line 12, in h1
    pdf.set_font_size(20)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 621, in set_font_size
    self._out(sprintf('BT /F%d %.2f Tf ET',self.current_font['i'],self.font_size_pt))
AttributeError: 'FPDF' object has no attribute 'current_font'
[2022-12-13 07:52:33,529] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=cereal_paper, task_id=create_pdf_task, execution_date=20221212T000000, start_date=20221213T075233, end_date=20221213T075233
[2022-12-13 07:52:33,536] {standard_task_runner.py:97} ERROR - Failed to execute job 24 for task create_pdf_task ('FPDF' object has no attribute 'current_font'; 263)
[2022-12-13 07:52:33,577] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-13 07:52:33,620] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
