[2022-12-12 17:26:52,161] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T17:26:47.179762+00:00 [queued]>
[2022-12-12 17:26:52,168] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T17:26:47.179762+00:00 [queued]>
[2022-12-12 17:26:52,169] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 17:26:52,169] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-12 17:26:52,170] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 17:26:52,177] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): create_pdf_task> on 2022-12-12 17:26:47.179762+00:00
[2022-12-12 17:26:52,180] {standard_task_runner.py:52} INFO - Started process 824 to run task
[2022-12-12 17:26:52,183] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'daily_paper', 'create_pdf_task', 'manual__2022-12-12T17:26:47.179762+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/morning-paper.py', '--cfg-path', '/tmp/tmp4dfngir6', '--error-file', '/tmp/tmpo7y_yzti']
[2022-12-12 17:26:52,185] {standard_task_runner.py:80} INFO - Job 234: Subtask create_pdf_task
[2022-12-12 17:26:52,224] {task_command.py:369} INFO - Running <TaskInstance: daily_paper.create_pdf_task manual__2022-12-12T17:26:47.179762+00:00 [running]> on host 6bb81baa0a52
[2022-12-12 17:26:52,273] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=akash.khamkar40@gmail.com
AIRFLOW_CTX_DAG_OWNER=akashk
AIRFLOW_CTX_DAG_ID=daily_paper
AIRFLOW_CTX_TASK_ID=create_pdf_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T17:26:47.179762+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-12T17:26:47.179762+00:00
[2022-12-12 17:26:52,274] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/morning_paper_src/pdf.py", line 26, in create_pdf
    pdf.add_font('SpecialElite', '', 'SpecialElite.ttf', uni=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/fpdf/fpdf.py", line 469, in add_font
    raise RuntimeError("TTF Font file not found: %s" % fname)
RuntimeError: TTF Font file not found: SpecialElite.ttf
[2022-12-12 17:26:52,285] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_paper, task_id=create_pdf_task, execution_date=20221212T172647, start_date=20221212T172652, end_date=20221212T172652
[2022-12-12 17:26:52,292] {standard_task_runner.py:97} ERROR - Failed to execute job 234 for task create_pdf_task (TTF Font file not found: SpecialElite.ttf; 824)
[2022-12-12 17:26:52,315] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-12 17:26:52,342] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
